# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

# Octo STS policy for Materializer dev environment
# Service account: materializer@mattmoor-chainguard.iam.gserviceaccount.com

issuer: https://accounts.google.com
subject: "101531125799729172566"

permissions:
  # Create and push branches with solutions
  contents: write

  # Create and update pull requests
  pull_requests: write

  # Update issues with PR links
  issues: write

  # Trigger and manage GitHub Actions workflows
  workflows: write

repositories:
  - mattmoor-bespin-playground
